---
title: "data_wrangling_i"
author: "Anyu Zhu"
date: "9/23/2021"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```
## Import some data

I want to import `FAS_litters.csv`
```{r}
litters_df = read_csv("data_import_examples/FAS_litters.csv")
```

clean the names.
```{r}
litters_df = janitor::clean_names(litters_df)
names(litters_df)
```

look at the dataset
```{r, eval=FALSE}
View(litters_df)
# skimmer package: overview of dataset
skimr::skim(litters_df)
```

## Arguments in `read_csv`
```{r eval=FALSE}
litters_df = read_csv("data_import_examples/FAS_litters.csv",
                      skip = 5,
                      col_names = FALSE)
```
## Parsing columns
```{r}
litters_data = read_csv(file = "data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

## Reading from Excel
```{r}
mlb11_df = read_excel("data_import_examples/mlb11.xlsx")
```

## LotR word read
```{r}
fellow_df = read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

## read a SAS file
```{r, eval=FALSE}
pulsa_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")
```

## export data
```{r}
write_csv(fellow_df, "data_import_examples/fellowship_words.csv")
```

## data manipulation

# Import some data
Import `FAS_litters.csv
`
```{r}
litters_df = read_csv(file = "data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data_import_examples/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```
## `select`
select some columns.

```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd18_weight)

select(litters_df, group, gd0_weight:gd_of_birth)
select(litters_df, group, starts_with("pups"))
select(litters_df, -litter_number) # eliminate column

select(litters_df, GROUP = group, litter_number)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, everything())

relocate(litters_df, litter_number)
```

## pups data
```{r}
select(pups_df, litter_number, sex, pd_ears)

pull(litters_df, group)
```

## `filter`

```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)
filter(litters_df, pups_survive != 4)
filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"))
filter(litters_df, group == "Con7", gd_of_birth == 20) # and
filter(litters_df, group == "Con7" | gd_of_birth == 20) # or

drop_na(litters_df)
drop_na(litters_df, gd0_weight)

filter(pups_df, sex == 1)
```
## `mutate`
add or change columns

```{r}
mutate(
  litters_df, 
  weight_change = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## `arrange`
rearrange the data
```{r}
arrange(litters_df, desc(gd0_weight))
arrange(litters_df, gd_of_birth, gd0_weight)
```
## Pipes
```{r}
litters_data_row = read_csv("data_import_examples/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_row )
litters_select = select(litters_clean_name, group, pups_survive)
litters_filtered = filter(litters_select, group == "Con7")

litters_df = 
  read_csv("data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>% # just move on with current df
  select(group, pups_survive) %>%
  filter(group == "Con7")


litters_df = 
  read_csv("data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>%
  drop_na(weight_change) %>%
  filter(group %in% c("con7", "con8")) %>%
  select(litter_number, group, weight_change, everything())
```



